### ISSUE TITLE
Loading credentials from yaml file doesn't seem to work

### ISSUE THREAD

**Issue by nikagl** [molobrakos/volvooncall#3]
When I create a new ".credentials.yaml" file based on the ".credentials.template.yaml" with my credentials in it, it doesn't work (the ImportError is caught; that's why I added the additional Logger line). Adding them from command line works fine...

Regards,

Nika.

**Comment by molobrakos** [comment]
I think you miss yaml. (`pip install pyyaml` or `apt-get install python-yaml`). I didn't want to add it as a dependency, since it is only needed when calling from the command line (not when using as a lib). I guess it could print some error message. Or maybe switch the config to json, which is available in the standard lib.

**Comment by nikagl** [comment]
Hmm... tried installing it (on Windows) using "python -m pip install pyyaml", but now I get an access denied error. I added the following logging:

`_LOGGER.debug("Logging in with username %s and password %s.", username, password)`

And it returns:

`DEBUG:__main__:Logging in with username username and password password.`

Regards,

Nika.

**Comment by molobrakos** [comment]
removed this dependency now.
