### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by wewen79** [molobrakos/volvooncall#39]
I would love to be able to see my temp from my HA. Do you think this would be implementable?

**Comment by molobrakos** [comment]
You have to provide information on the key/value pair returned in the JSON output from the server corresponding to the temperature you want to display.

**Comment by molobrakos** [comment]
I don't see any temperature returned from the server in my case. Maybe it differs between models? I believe the outdoor temperature displayed in the app is returned by some third party service based on the gps coordinates.

**Comment by wewen79** [comment]
I have not been able to get any temp information either. But I might ask
the developers directly. I work there. Not with software thought. I will
return the answer to you.

**Comment by molobrakos** [comment]
If you find any python lib that returns the temperature (e.g. from smhi or yr.no) given lat/lon, I guess we could integrate it somehow (there is already support for geo lookup). Otherwise you could push the temperature to HA using mosquitto_pub and a shell script using e.g. curl to fetch the temperature from some api (both smhi and yr provides a api).

**Comment by wewen79** [comment]
You are swedish right? Från volvo on call sharepointen på volvo

"Consumer & Enterprise Digital Service Support - VOC Temperature

Svar ftaget från SNOW ticket där temperatur inte visades i VOC appen:



Då appen hämtar väderdata direct från  HERE Weather så har vi lite svårt
att se vari felet ligger. Vi kan se I loggarna att bilen skickar en GPS
position till appen och sen skickar appen den positionen till HERE och de
returnerar temperature till appen.
Jag har kollat lite med de appansvariga och svaret de ger så här långt är
följande:

Det är svårt att svara bestämt på vad fel är, men det finns flera
möjligheter:
• Det troligaste är att HERE inte levererar temperaturdata för den aktuella
positionen på det sätt som appen förväntar sig.
• Mindre troligt: Det går inte att ansluta till HERE (trots att detta går
att ansluta till andra stället). Svårt att hitta en anledning till detta,
men skulle möjligen kunna bero på problem med certifikat i iOS.

Så det svar vi kan ge så här långt, är att prova med lite olika
destinationer (gärna centrala orter) och se om det ger någon temperatur i
appen?
I övrigt så är det nog så att man får gå igenom telefonen och se så inga
HERE eller Accuweather sidor är blockade och se ifall man dels når HERE
Weather (https://www.accuweather.com/en/se/sweden-weather) och även om man
kan köra scriptet på den här sidan:
https://developer.here.com/api-explorer/rest/auto_weather    (klicka på
"send request" och då skall den svarta rutan uppdateras med väderkod.)
Några andra enkla felsökningsmetoder vet vi tyvärr inte om?"

Den mån 14 jan. 2019 kl 19:03 skrev Erik Eriksson <notifications@github.com

**Comment by molobrakos** [comment]
Since the app displays minus degrees during the winter even when the car is parked in a warm garage I have assumed they are using an external service based on the gps position :-) This seems to confirm that assumption. There is a thermometer available in the car (the outdoor temperature is displayed on the dashboard when driving), and I guess it theoretically could be published to the server and made available via the API as well on newer models, but I don't know anything about that, at least it is not on the car I have access to.

**Comment by wewen79** [comment]
It ok. I can use another external weather provider. You don't have to take
time for this task. Thanks anyway.
